GET http://localhost:8080/api/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjY1NjkxNTksImlhdCI6MTYyNjUyNTk1OSwidXNlcl9pZCI6MX0.jA0kEB1WEwXnSAaUsifz9f7DYegYjkhImwDyjywJej0

{
"title": "Список дел",
"description": "нужно сделать"
}
