PUT http://localhost:8080/api/lists/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjY4NDk3OTQsImlhdCI6MTYyNjgwNjU5NCwidXNlcl9pZCI6MX0.edTzltn-jPfI7JBil2akMbQDqUXTLj6wwQ3x8N0ZVOM

{
"title": "список дел",
"description": "нужно сделать"
}
