POST http://localhost:8080/api/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjU3MjE0NTEsImlhdCI6MTYyNTY3ODI1MSwidXNlcl9pZCI6MX0.qeTP2yvb9BBy0p_7vd9jx7J7E2POpxRT1ayp3eiu_mU

